// Created by Jesse on 12/29/2023.
#pragma once

namespace Izuma
{
#define IZ_KEY_BACKSPACE           8
#define IZ_KEY_TAB                 9
#define IZ_KEY_ENTER              13
#define IZ_KEY_SHIFT              16
#define IZ_KEY_CTRL               17
#define IZ_KEY_ALT                18
#define IZ_KEY_PAUSE              19
#define IZ_KEY_CAPS_LOCK          20
#define IZ_KEY_ESCAPE             27
#define IZ_KEY_SPACE              32
#define IZ_KEY_PAGE_UP            33
#define IZ_KEY_PAGE_DOWN          34
#define IZ_KEY_END                35
#define IZ_KEY_HOME               36
#define IZ_KEY_LEFT_ARROW         37
#define IZ_KEY_UP_ARROW           38
#define IZ_KEY_RIGHT_ARROW        39
#define IZ_KEY_DOWN_ARROW         40
#define IZ_KEY_PRINT_SCREEN       44
#define IZ_KEY_INSERT             45
#define IZ_KEY_DELETE             46
#define IZ_KEY_0                  48
#define IZ_KEY_1                  49
#define IZ_KEY_2                  50
#define IZ_KEY_3                  51
#define IZ_KEY_4                  52
#define IZ_KEY_5                  53
#define IZ_KEY_6                  54
#define IZ_KEY_7                  55
#define IZ_KEY_8                  56
#define IZ_KEY_9                  57
#define IZ_KEY_A                  65
#define IZ_KEY_B                  66
#define IZ_KEY_C                  67
#define IZ_KEY_D                  68
#define IZ_KEY_E                  69
#define IZ_KEY_F                  70
#define IZ_KEY_G                  71
#define IZ_KEY_H                  72
#define IZ_KEY_I                  73
#define IZ_KEY_J                  74
#define IZ_KEY_K                  75
#define IZ_KEY_L                  76
#define IZ_KEY_M                  77
#define IZ_KEY_N                  78
#define IZ_KEY_O                  79
#define IZ_KEY_P                  80
#define IZ_KEY_Q                  81
#define IZ_KEY_R                  82
#define IZ_KEY_S                  83
#define IZ_KEY_T                  84
#define IZ_KEY_U                  85
#define IZ_KEY_V                  86
#define IZ_KEY_W                  87
#define IZ_KEY_X                  88
#define IZ_KEY_Y                  89
#define IZ_KEY_Z                  90
#define IZ_KEY_LEFT_SUPER         91
#define IZ_KEY_RIGHT_SUPER        92
#define IZ_KEY_MENU               93
#define IZ_KEY_NUMPAD_0           96
#define IZ_KEY_NUMPAD_1           97
#define IZ_KEY_NUMPAD_2           98
#define IZ_KEY_NUMPAD_3           99
#define IZ_KEY_NUMPAD_4          100
#define IZ_KEY_NUMPAD_5          101
#define IZ_KEY_NUMPAD_6          102
#define IZ_KEY_NUMPAD_7          103
#define IZ_KEY_NUMPAD_8          104
#define IZ_KEY_NUMPAD_9          105
#define IZ_KEY_NUMPAD_MULT       106
#define IZ_KEY_NUMPAD_ADD        107
#define IZ_KEY_NUMPAD_ENTER      108
#define IZ_KEY_NUMPAD_MINUS      109
#define IZ_KEY_NUMPAD_DECIMAL    110
#define IZ_KEY_NUMPAD_DIVIDE     111
#define IZ_KEY_F1                112
#define IZ_KEY_F2                113
#define IZ_KEY_F3                114
#define IZ_KEY_F4                115
#define IZ_KEY_F5                116
#define IZ_KEY_F6                117
#define IZ_KEY_F7                118
#define IZ_KEY_F8                119
#define IZ_KEY_F9                120
#define IZ_KEY_F10               121
#define IZ_KEY_F11               122
#define IZ_KEY_F12               123
#define IZ_KEY_F13               124
#define IZ_KEY_F14               125
#define IZ_KEY_F15               126
#define IZ_KEY_F16               127
#define IZ_KEY_F17               128
#define IZ_KEY_F18               129
#define IZ_KEY_F19               130
#define IZ_KEY_F20               131
#define IZ_KEY_F21               132
#define IZ_KEY_F22               133
#define IZ_KEY_F23               134
#define IZ_KEY_F24               135
#define IZ_KEY_NUM_LOCK          144
#define IZ_KEY_SCROLL_LOCK       145
#define IZ_KEY_LEFT_SHIFT        160
#define IZ_KEY_RIGHT_SHIFT       161
#define IZ_KEY_LEFT_CTRL         162
#define IZ_KEY_RIGHT_CTRL        163
#define IZ_KEY_LEFT_ALT          164
#define IZ_KEY_RIGHT_ALT         165
#define IZ_KEY_COLON             186
#define IZ_KEY_EQUALS            187
#define IZ_KEY_COMMA             188
#define IZ_KEY_MINUS             189
#define IZ_KEY_PERIOD            190
#define IZ_KEY_FORWARD_SLASH     191
#define IZ_KEY_GRAVE             192
#define IZ_KEY_LEFT_BRACKET      219
#define IZ_KEY_BACK_SLASH        220
#define IZ_KEY_RIGHT_BRACKET     221
#define IZ_KEY_APOSTROPHE        222
}